services:
  redis-compose:
    image: redis
    command: redis-server
    container_name: redis
    env_file:
      - "/backend/.env"
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17
    container_name: postgres
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # golang-project:
  #   container_name: "my-project"
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   image: golang-project
  #   depends_on:
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"

volumes:
  postgres_data:
