package utils

import "errors"

var (
	ErrInvalidToken              = errors.New("invalid token")
	ErrIdIsRequired              = errors.New("id is required")
	ErrPollNotFound              = errors.New("poll not found")
	ErrDuplicatedVote            = errors.New("duplicated vote")
	ErrTokenNotValidYet          = errors.New("token not valid")
	ErrMalformedToken            = errors.New("malformed token")
	ErrOptionsNotFound           = errors.New("option not found")
	ErrNameIsRequired            = errors.New("name is required")
	ErrPollIDMissing             = errors.New("poll id is missing")
	ErrInvalidCredentials        = errors.New("invalid credentials")
	ErrInvalidTokenClaim         = errors.New("invalid token claim")
	ErrInvalidHashFormat         = errors.New("invalid hash format")
	ErrIncompatibleVersion       = errors.New("incompatible version")
	ErrInvalidRequestBody        = errors.New("invalid request body")
	ErrGenericError              = errors.New("something went wrong")
	ErrParsingToken              = errors.New("error parsing token!")
	ErrInvalidExpiredToken       = errors.New("invalid expired token")
	ErrInvalidTokenSignature     = errors.New("invalid token signature")
	ErrFailedToGenerateToken     = errors.New("failed to generate token")
	ErrOptionsIncorrectSize      = errors.New("options must be at least 2")
	ErrRunUpMigrations           = errors.New("could not run up migrations")
	ErrOptionsIsRequired         = errors.New("option name cannot be blank")
	ErrInvalidTokenSigningMethod = errors.New("invalid token signing method")
	ErrInvalidLogin              = errors.New("invalid email and/or password")
	ErrInvalidEmail              = errors.New("invalid email, cannot be empty")
	ErrCreateSourceDriver        = errors.New("could not create source driver")
	ErrCreateMigrateDriver       = errors.New("could not create migrate driver")
	ErrCreateMigrateInstance     = errors.New("could not create migrate instance")
	ErrPollExpired               = errors.New("this poll has expired and no longer accepts votes")
	ErrInvalidPassword           = errors.New("invalid password, must be at least 5 characters long")
	ErrForbidden                 = errors.New("access denied! you don't have permission to access this resource on this server")
	ErrUnauthorized              = errors.New("the server requires you to authenticate, but your request included missing, expired, or invalid credentials")
)
